package(default_visibility = ["//visibility:public"])

cc_library(
        name = "mem",
        srcs = glob(["*.c", "*.h"]),
		hdrs = ["mem.h"],
		strip_include_prefix = ".",
		deps = [
			"//lib/core"
		]
)


