package(default_visibility = ["//visibility:public"])

cc_library(
        name = "hash",
		srcs = glob(["*.c"]),
        hdrs = ["hash.h"],
		strip_include_prefix = ".",
		deps = [
			"//lib/core"
		]
)


